services:
    Doctrine\DBAL\Connection:
        factory: ['Doctrine\DBAL\DriverManager', 'getConnection']
        arguments:
            - { driver: 'pdo_sqlite', path: '%kernel.project_dir%/var/data.test.sqlite' }
